// Package interop is the Phase 8b acceptance gate: it proves the TS
// vault-client library actually interoperates with the real Go
// `loadoutd`/CLI on the wire (age blob, ustar tar, push protocol), and
// that the no-secrets guarantee holds across the language boundary.
//
// SANDBOX: every test here uses only a t.TempDir() vault, dummy age
// keys, and a dummy secret plaintext. Nothing here ever touches a real
// $HOME or a real ~/.loadout. Read-only fixtures live under
// web/lib/vault/testdata/ (gitignored, generated by these tests and by
// scripts/interop-test.sh — never committed).
package interop

import (
	"bytes"
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"runtime"
	"testing"

	"filippo.io/age"

	"loadout.dev/loadout/internal/vault"
)

// Three fixed DUMMY age X25519 keypairs, generated once with a throwaway
// age.GenerateX25519Identity() call (never age-keygen) and hardcoded here.
// They are test-only: no real device or vault ever uses them. The exact
// same six strings are hardcoded again in web/lib/vault/interop.test.ts, so
// both languages encrypt to, and decrypt with, the identical keys.
const (
	fullAIdentity  = "AGE-SECRET-KEY-1X9YXLV7SAP5EG64SCTSR7GCDA8R0TL5WH7VN7TTYSQJG0AYU3KQQ37FRM0"
	fullARecipient = "age1frumec9kvutf4svkaz35f7h3ndxqqfzztqsfsnp84p9dkduggcysa4jl6h"

	fullBIdentity  = "AGE-SECRET-KEY-10U0LVU3WWZ8TR8VE7Q33ZVDZAMFC56PN5047FJE9VV4049U9G4YS8M0DK6"
	fullBRecipient = "age1jl0dqa922qe5xdrppn8dmkahehcxq7zquwjpfyt3z5nvp0hvjqas59dtdf"

	nosecIdentity  = "AGE-SECRET-KEY-17SDYU3TLT6N2JRS9QY2ASPRVDECD0MT3F6JNZFKN6AZ3FAC3JACSRRF6NM"
	nosecRecipient = "age1ffq3k43364marx29alvcyyu2eck50j4nyrhy2nnqr7xpsqjudvpsyk28cw"
)

// The known content every fixture carries. secretPlaintext is a dummy
// value, never a real credential. editedMemoryBody is the exact string
// web/lib/vault/interop.test.ts writes into memory/note when it proves the
// TS -> Go write direction; it is hardcoded identically on both sides, the
// same way the keypairs above are.
const (
	secretPlaintext  = "INTEROP-SECRET-PLAINTEXT"
	skillBody        = "Demo skill body for the phase 8b Go<->TS interop test.\n"
	skillFileContent = "---\nname: demo\ndescription: a demo skill for interop\n---\n" + skillBody
	memoryBody       = "Original memory body for the phase 8b Go<->TS interop test.\n"
	editedMemoryBody = "EDITED-BY-TS"
)

// fixtureData is go-fixture.json's shape: the known plaintext values a TS
// test can assert against directly, instead of hardcoding a second copy
// that could drift from what Go actually wrote.
type fixtureData struct {
	SecretName       string `json:"secretName"`
	SecretPlaintext  string `json:"secretPlaintext"`
	SkillAddress     string `json:"skillAddress"`
	SkillBody        string `json:"skillBody"`
	MemoryAddress    string `json:"memoryAddress"`
	MemoryBody       string `json:"memoryBody"`
	EditedMemoryBody string `json:"editedMemoryBody"`
}

// testdataDir returns web/lib/vault/testdata's absolute path, resolved
// from this source file's own location rather than the process's current
// directory, so it is correct no matter how `go test` is invoked.
func testdataDir() string {
	_, file, _, _ := runtime.Caller(0)
	return filepath.Join(filepath.Dir(file), "..", "..", "web", "lib", "vault", "testdata")
}

// newIdentityDir builds a throwaway directory holding only one
// device.key, so it can stand in for a *vault.Vault wherever a test needs
// one device's own identity (UnpackSnapshot, DecryptSecret) without a real
// vault around it (no manifest, no history — neither is read by either
// function).
func newIdentityDir(t *testing.T, identity string) *vault.Vault {
	t.Helper()
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "device.key"), []byte(identity+"\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	return &vault.Vault{Root: dir}
}

// writeDeviceKey overwrites v's device.key with identity, so v acts as
// that specific dummy device instead of whatever key vault.Init would
// otherwise generate for it.
func writeDeviceKey(t *testing.T, v *vault.Vault, identity string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(v.Root, "device.key"), []byte(identity+"\n"), 0o600); err != nil {
		t.Fatal(err)
	}
}

// fixturesPresent reports whether every file TestWriteFixturesForTS
// produces already exists in dir.
func fixturesPresent(dir string) bool {
	for _, name := range []string{"go-snapshot.age", "go-value.age", "go-fixture.json"} {
		if _, err := os.Stat(filepath.Join(dir, name)); err != nil {
			return false
		}
	}
	return true
}

// TestWriteFixturesForTS is the Go -> TS half of the interop gate
// (scripts/interop-test.sh step 1). It builds a temp vault with one
// skill, one memory item, a three-device roster (two full, one
// no-secrets), and one secret encrypted to the full devices only, packs
// it, and writes the results where web/lib/vault/interop.test.ts reads
// them from.
//
// age.Encrypt randomizes its output on every call, so re-running this
// build on every invocation would silently invalidate any ts-snapshot.age
// a prior scripts/interop-test.sh run already produced FROM this exact
// go-value.age (an unfiltered `go test ./...`, run right after the
// harness, would otherwise re-run this test, mint a fresh value.age, and
// make TestGoReadsTSSnapshot's byte-identity check fail for a reason that
// has nothing to do with either language's correctness). So this test
// only builds fresh fixtures when none exist yet; scripts/interop-test.sh
// clears web/lib/vault/testdata/ first, so a real run of the gate always
// gets a genuinely fresh build. Either way, the no-secrets guarantee is
// re-checked against whatever fixtures end up on disk.
func TestWriteFixturesForTS(t *testing.T) {
	dir := testdataDir()
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}

	if fixturesPresent(dir) {
		t.Log("interop testdata already present: reusing it rather than " +
			"minting fresh (randomized) age ciphertext that could stop " +
			"matching a ts-snapshot.age a prior harness run already built")
	} else {
		buildFixtures(t, dir)
	}

	assertGoSideGuaranteeHolds(t, dir)
}

// buildFixtures does the actual vault construction and fixture writing
// for TestWriteFixturesForTS.
func buildFixtures(t *testing.T, dir string) {
	t.Helper()

	// SANDBOX: a temp HOME and a temp LOADOUT_HOME, so nothing here can
	// ever resolve to the real ~/.loadout even by accident.
	t.Setenv("HOME", t.TempDir())
	t.Setenv("LOADOUT_HOME", filepath.Join(t.TempDir(), "loadout-home"))

	root := filepath.Join(t.TempDir(), "vault")
	v, err := vault.Init(root)
	if err != nil {
		t.Fatal(err)
	}
	// This vault IS full_a for the purposes of this fixture: it holds
	// full_a's own identity, so it may add a secret as a full device.
	writeDeviceKey(t, v, fullAIdentity)

	skillDir := filepath.Join(v.SkillsDir(), "demo")
	if err := os.MkdirAll(skillDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(skillDir, "SKILL.md"), []byte(skillFileContent), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(v.MemoryDir(), "note.md"), []byte(memoryBody), 0o644); err != nil {
		t.Fatal(err)
	}

	if err := vault.AddToRoster(v, "FULL_A", fullARecipient, vault.RoleFull); err != nil {
		t.Fatal(err)
	}
	if err := vault.AddToRoster(v, "FULL_B", fullBRecipient, vault.RoleFull); err != nil {
		t.Fatal(err)
	}
	if err := vault.AddToRoster(v, "NOSEC", nosecRecipient, vault.RoleNoSecrets); err != nil {
		t.Fatal(err)
	}

	// secretRecipients (internal/vault/secret.go) reads this roster and
	// excludes any RoleNoSecrets device, so this call alone is what keeps
	// NOSEC off value.age's recipient list.
	if err := vault.AddSecret(v, "k", "interop", "used only by the phase 8b interop test", "", "interop-test", nil, []byte(secretPlaintext)); err != nil {
		t.Fatal(err)
	}

	if err := vault.Snapshot(v, "add interop fixtures"); err != nil {
		t.Fatal(err)
	}

	blob, _, err := vault.PackSnapshot(v)
	if err != nil {
		t.Fatal(err)
	}
	valueAge, err := os.ReadFile(filepath.Join(v.SecretsDir(), "k", "value.age"))
	if err != nil {
		t.Fatal(err)
	}

	if err := os.WriteFile(filepath.Join(dir, "go-snapshot.age"), blob, 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "go-value.age"), valueAge, 0o644); err != nil {
		t.Fatal(err)
	}

	fixture := fixtureData{
		SecretName:       "k",
		SecretPlaintext:  secretPlaintext,
		SkillAddress:     "skill/demo",
		SkillBody:        skillBody,
		MemoryAddress:    "memory/note",
		MemoryBody:       memoryBody,
		EditedMemoryBody: editedMemoryBody,
	}
	encoded, err := json.MarshalIndent(fixture, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "go-fixture.json"), encoded, 0o644); err != nil {
		t.Fatal(err)
	}
}

// assertGoSideGuaranteeHolds proves the no-secrets guarantee on the Go
// side, straight off whatever fixtures currently sit in dir: a full
// device (full_a) decrypts secret k to the known plaintext; the
// no-secrets device (nosec) can unpack the outer snapshot (its recipient
// IS on the outer tar's list) but cannot decrypt the secret inside it,
// either through DecryptSecret or a raw age.Decrypt of value.age.
func assertGoSideGuaranteeHolds(t *testing.T, dir string) {
	t.Helper()

	blob, err := os.ReadFile(filepath.Join(dir, "go-snapshot.age"))
	if err != nil {
		t.Fatal(err)
	}
	valueAge, err := os.ReadFile(filepath.Join(dir, "go-value.age"))
	if err != nil {
		t.Fatal(err)
	}

	fullAVault := newIdentityDir(t, fullAIdentity)
	if err := vault.UnpackSnapshot(fullAVault, blob, fullAVault.Root); err != nil {
		t.Fatalf("a full device must unpack its own snapshot: %v", err)
	}
	plaintext, err := vault.DecryptSecret(fullAVault, "k")
	if err != nil {
		t.Fatalf("a full device must decrypt secret k: %v", err)
	}
	if string(plaintext) != secretPlaintext {
		t.Fatalf("decrypted secret = %q, want %q", plaintext, secretPlaintext)
	}

	nosecVault := newIdentityDir(t, nosecIdentity)
	if err := vault.UnpackSnapshot(nosecVault, blob, nosecVault.Root); err != nil {
		t.Fatalf("the no-secrets device must still be able to unpack the outer snapshot: %v", err)
	}
	if _, err := vault.DecryptSecret(nosecVault, "k"); err == nil {
		t.Fatal("the no-secrets device must not decrypt secret k via DecryptSecret")
	}
	nosecAgeIdentity, err := age.ParseX25519Identity(nosecIdentity)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := age.Decrypt(bytes.NewReader(valueAge), nosecAgeIdentity); err == nil {
		t.Fatal("a raw age.Decrypt of go-value.age must fail for the no-secrets identity")
	}
}

// TestGoReadsTSSnapshot is the TS -> Go half of the interop gate
// (scripts/interop-test.sh step 3). web/lib/vault/interop.test.ts (step 2)
// parses go-snapshot.age's entries, edits memory/note to editedMemoryBody,
// repacks the tar with its own writer, and encrypts it to all three dummy
// devices, writing the result to ts-snapshot.age. This test proves Go's
// real UnpackSnapshot/DecryptSecret accept that TS-produced tar, that the
// edit landed, that everything else (the skill, and every secrets/**
// byte) survived untouched, and that the no-secrets guarantee still holds
// after this round trip through a TS tar writer.
func TestGoReadsTSSnapshot(t *testing.T) {
	dir := testdataDir()
	tsBlob, err := os.ReadFile(filepath.Join(dir, "ts-snapshot.age"))
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			t.Skip("run scripts/interop-test.sh — ts-snapshot.age not generated yet")
		}
		t.Fatal(err)
	}
	goValueAge, err := os.ReadFile(filepath.Join(dir, "go-value.age"))
	if err != nil {
		t.Fatal(err)
	}

	nosecVault := newIdentityDir(t, nosecIdentity)
	if err := vault.UnpackSnapshot(nosecVault, tsBlob, nosecVault.Root); err != nil {
		t.Fatalf("UnpackSnapshot of the TS-produced tar must succeed, with no unsafePathErr: %v", err)
	}

	gotMemory, err := os.ReadFile(filepath.Join(nosecVault.Root, "memory", "note.md"))
	if err != nil {
		t.Fatal(err)
	}
	if string(gotMemory) != editedMemoryBody {
		t.Fatalf("memory/note.md = %q, want the TS-edited body %q", gotMemory, editedMemoryBody)
	}

	gotSkill, err := os.ReadFile(filepath.Join(nosecVault.Root, "skills", "demo", "SKILL.md"))
	if err != nil {
		t.Fatal(err)
	}
	if string(gotSkill) != skillFileContent {
		t.Fatalf("skills/demo/SKILL.md was altered by the TS round trip:\ngot:  %q\nwant: %q", gotSkill, skillFileContent)
	}

	gotValueAge, err := os.ReadFile(filepath.Join(nosecVault.Root, "secrets", "k", "value.age"))
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(gotValueAge, goValueAge) {
		t.Fatal("secrets/k/value.age must survive the TS round trip byte-for-byte: the browser must carry secret bytes through unchanged, never regenerate them")
	}

	// The no-secrets guarantee, Go side, after a browser (TS) round trip.
	if _, err := vault.DecryptSecret(nosecVault, "k"); err == nil {
		t.Fatal("the no-secrets device must not decrypt secret k even after a TS round trip")
	}
	nosecAgeIdentity, err := age.ParseX25519Identity(nosecIdentity)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := age.Decrypt(bytes.NewReader(gotValueAge), nosecAgeIdentity); err == nil {
		t.Fatal("a raw age.Decrypt of the round-tripped value.age must still fail for the no-secrets identity")
	}

	// A full device must still decrypt the secret after the round trip:
	// proof the browser never regenerated or corrupted it.
	fullAVault := newIdentityDir(t, fullAIdentity)
	if err := vault.UnpackSnapshot(fullAVault, tsBlob, fullAVault.Root); err != nil {
		t.Fatalf("UnpackSnapshot for the full device must also succeed: %v", err)
	}
	plaintext, err := vault.DecryptSecret(fullAVault, "k")
	if err != nil {
		t.Fatalf("a full device must still decrypt the secret after the TS round trip: %v", err)
	}
	if string(plaintext) != secretPlaintext {
		t.Fatalf("decrypted secret after round trip = %q, want %q", plaintext, secretPlaintext)
	}
}
