import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { AgeDecryptError, decrypt, encryptTo } from "./age.js";
import { applyEdit, outerRecipients, parseVault } from "./model.js";
import { readTar, writeTar } from "./tar.js";

/*
 * The Go <-> TS cross-language interop gate (Phase 8b, task 8): the
 * acceptance proof that this TS vault-client library actually
 * interoperates with the real Go loadoutd/CLI on the wire (age blob,
 * ustar tar, push protocol), and that the no-secrets guarantee holds
 * across the language boundary — not just within one language's own unit
 * tests.
 *
 * Fixtures live in ./testdata/ (gitignored, generated by
 * internal/interop/interop_test.go and by this file). The whole suite
 * below SKIPS with a clear name when go-snapshot.age is absent, so
 * `npm test` stays green on a clean checkout. Run
 * `bash scripts/interop-test.sh` from the repo root to generate fixtures
 * and exercise both directions for real.
 */

const TESTDATA_DIR = join(dirname(fileURLToPath(import.meta.url)), "testdata");

// The same three dummy age X25519 keypairs hardcoded in
// internal/interop/interop_test.go. They are test-only: no real device or
// vault ever uses them. Both languages must encrypt to, and decrypt with,
// the identical keys for this gate to mean anything.
const FULL_A = {
  identity:
    "AGE-SECRET-KEY-1X9YXLV7SAP5EG64SCTSR7GCDA8R0TL5WH7VN7TTYSQJG0AYU3KQQ37FRM0",
  recipient: "age1frumec9kvutf4svkaz35f7h3ndxqqfzztqsfsnp84p9dkduggcysa4jl6h",
};
const FULL_B = {
  identity:
    "AGE-SECRET-KEY-10U0LVU3WWZ8TR8VE7Q33ZVDZAMFC56PN5047FJE9VV4049U9G4YS8M0DK6",
  recipient: "age1jl0dqa922qe5xdrppn8dmkahehcxq7zquwjpfyt3z5nvp0hvjqas59dtdf",
};
const NOSEC = {
  identity:
    "AGE-SECRET-KEY-17SDYU3TLT6N2JRS9QY2ASPRVDECD0MT3F6JNZFKN6AZ3FAC3JACSRRF6NM",
  recipient: "age1ffq3k43364marx29alvcyyu2eck50j4nyrhy2nnqr7xpsqjudvpsyk28cw",
};

// The exact string this file writes into memory/note to prove the
// TS -> Go write direction. Hardcoded identically in
// internal/interop/interop_test.go, so both sides agree on what the
// round-tripped file must hold without a file carrying the value across.
const EDITED_MEMORY_BODY = "EDITED-BY-TS";

/** go-fixture.json's shape (internal/interop/interop_test.go's fixtureData):
 * the known plaintext values Go actually wrote, so this file can assert
 * exact expected content without hardcoding a second copy that could
 * drift from what Go wrote. */
interface GoFixture {
  secretName: string;
  secretPlaintext: string;
  skillAddress: string;
  skillBody: string;
  memoryAddress: string;
  memoryBody: string;
  editedMemoryBody: string;
}

const goSnapshotPath = join(TESTDATA_DIR, "go-snapshot.age");
const goValuePath = join(TESTDATA_DIR, "go-value.age");
const goFixturePath = join(TESTDATA_DIR, "go-fixture.json");
const tsSnapshotPath = join(TESTDATA_DIR, "ts-snapshot.age");

const goFixturesPresent =
  existsSync(goSnapshotPath) && existsSync(goValuePath) && existsSync(goFixturePath);

// Reads the three Go-written fixtures fresh. Called only from inside an
// `it` body (never at describe-collection time): `describe.skipIf` still
// calls the describe callback below to discover its child tests even when
// every one of them will be skipped, so any file read at that outer level
// would throw ENOENT on a clean checkout before the skip ever takes
// effect. Reading lazily, inside each test, means a skipped test's body
// never runs at all, and so never touches the filesystem.
function loadGoFixtures(): {
  goSnapshot: Uint8Array;
  goValueAge: Uint8Array;
  fixture: GoFixture;
} {
  return {
    goSnapshot: new Uint8Array(readFileSync(goSnapshotPath)),
    goValueAge: new Uint8Array(readFileSync(goValuePath)),
    fixture: JSON.parse(readFileSync(goFixturePath, "utf-8")) as GoFixture,
  };
}

describe.skipIf(!goFixturesPresent)(
  "Go <-> TS snapshot interop (run `bash scripts/interop-test.sh` from the repo root if this is skipped)",
  () => {
    it("reads the Go snapshot", async () => {
      const { goSnapshot, goValueAge, fixture } = loadGoFixtures();
      const tar = await decrypt(goSnapshot, NOSEC.identity);
      const entries = readTar(tar);
      const parsedVault = parseVault(entries);

      const skill = parsedVault.items.find((item) => item.address === fixture.skillAddress);
      if (!skill) throw new Error(`expected an item at "${fixture.skillAddress}"`);
      expect(skill.body).toBe(fixture.skillBody);

      const memory = parsedVault.items.find((item) => item.address === fixture.memoryAddress);
      if (!memory) throw new Error(`expected an item at "${fixture.memoryAddress}"`);
      expect(memory.body).toBe(fixture.memoryBody);

      const secretMeta = parsedVault.secrets.find((secret) => secret.name === fixture.secretName);
      if (!secretMeta) throw new Error(`expected a secret named "${fixture.secretName}"`);

      const valueEntry = entries.find(
        (entry) => entry.name === `secrets/${fixture.secretName}/value.age`,
      );
      if (!valueEntry) throw new Error("expected a secrets/*/value.age tar entry");
      expect(valueEntry.type).toBe("file");

      // THE NO-SECRETS GUARANTEE, TS SIDE: the no-secrets device holds the
      // secret's ciphertext bytes right here (it just read them out of the
      // tar above), but its own identity is never one of value.age's
      // recipients, so decrypting it directly must fail.
      await expect(decrypt(valueEntry.bytes, NOSEC.identity)).rejects.toThrow(
        AgeDecryptError,
      );

      // A full device's identity DOES decrypt the same value.age (the
      // standalone copy Go also wrote) to the known plaintext.
      const plaintext = await decrypt(goValueAge, FULL_A.identity);
      expect(new TextDecoder().decode(plaintext)).toBe(fixture.secretPlaintext);
    });

    it("writes a snapshot Go can read", async () => {
      const { goSnapshot, fixture } = loadGoFixtures();
      const tar = await decrypt(goSnapshot, NOSEC.identity);
      const entries = readTar(tar);
      const parsedVault = parseVault(entries);

      // The recipients for the outer re-encryption come from the roster
      // this file just decrypted and parsed — never invented or cached —
      // exactly as interop contract §6/§7 requires of a real dashboard.
      const recipients = outerRecipients(parsedVault.roster);
      expect([...recipients].sort()).toEqual(
        [FULL_A.recipient, FULL_B.recipient, NOSEC.recipient].sort(),
      );

      const edited = applyEdit(entries, fixture.memoryAddress, EDITED_MEMORY_BODY);
      const newTar = writeTar(edited);
      const newBlob = await encryptTo(newTar, recipients);

      writeFileSync(tsSnapshotPath, newBlob);
    });
  },
);
